## Spring actuator config
spring:
  application:
    name: transfer
#  profiles:
#    active: local
  endpoints:
    actuator:
      enabled: true
  management:
    endpoints:
      web:
        exposure:
          include: refresh
  config:
    import: "optional:configserver:"
    use-legacy-processing: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

